language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install

script:
  - php vendor/bin/php-cs-fixer fix --dry-run --ansi
  - php vendor/bin/phpunit --coverage-clover tests/logs/clover.xml --colors=always

after_success:
  - travis_retry php vendor/bin/php-coveralls
